[32;1mLogging data to /home/tete/work/new/data/HoppperPretrain/HoppperPretrain_s3/progress.txt[0m
[36;1mSaving config:
[0m
{
    "ac_kwargs":	{
        "hidden_sizes":	[
            64,
            64
        ]
    },
    "actor_critic":	"MLPActorCritic",
    "clip_ratio":	0.2,
    "demo_file":	"data/Hoppper/Hoppper1000.pickle",
    "env_fn":	"<function <lambda> at 0x7fca6cfb6620>",
    "epochs":	50,
    "exp_name":	"HoppperPretrain",
    "gamma":	0.99,
    "lam":	0.97,
    "logger":	{
        "<spinup.utils.logx.EpochLogger object at 0x7fca6cfbb278>":	{
            "epoch_dict":	{},
            "exp_name":	"HoppperPretrain",
            "first_row":	true,
            "log_current_row":	{},
            "log_headers":	[],
            "output_dir":	"/home/tete/work/new/data/HoppperPretrain/HoppperPretrain_s3",
            "output_file":	{
                "<_io.TextIOWrapper name='/home/tete/work/new/data/HoppperPretrain/HoppperPretrain_s3/progress.txt' mode='w' encoding='UTF-8'>":	{
                    "mode":	"w"
                }
            }
        }
    },
    "logger_kwargs":	{
        "exp_name":	"HoppperPretrain",
        "output_dir":	"/home/tete/work/new/data/HoppperPretrain/HoppperPretrain_s3"
    },
    "max_ep_len":	1000,
    "pi_epochs":	60,
    "pi_lr":	0.0003,
    "save_freq":	10,
    "seed":	3,
    "steps_per_epoch":	40000,
    "target_kl":	0.01,
    "train_pi_iters":	80,
    "train_v_iters":	80,
    "vf_epochs":	60,
    "vf_lr":	0.001
}
Traceback (most recent call last):
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'Hoppper-v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 269, in <module>
    logger_kwargs=logger_kwargs, demo_file=args.demo_file)
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 36, in pretrain
    env = env_fn()
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 265, in <lambda>
    pretrain(lambda: gym.make(args.env), actor_critic=core.MLPActorCritic,
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Hoppper-v2

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'Hoppper-v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 269, in <module>
    logger_kwargs=logger_kwargs, demo_file=args.demo_file)
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 36, in pretrain
    env = env_fn()
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 265, in <lambda>
    pretrain(lambda: gym.make(args.env), actor_critic=core.MLPActorCritic,
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Hoppper-v2

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'Hoppper-v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 269, in <module>
    logger_kwargs=logger_kwargs, demo_file=args.demo_file)
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 36, in pretrain
    env = env_fn()
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 265, in <lambda>
    pretrain(lambda: gym.make(args.env), actor_critic=core.MLPActorCritic,
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Hoppper-v2

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'Hoppper-v2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 269, in <module>
    logger_kwargs=logger_kwargs, demo_file=args.demo_file)
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 36, in pretrain
    env = env_fn()
  File "/home/tete/work/new/spinup/algos/pytorch/acdf_cuda/pretrain.py", line 265, in <lambda>
    pretrain(lambda: gym.make(args.env), actor_critic=core.MLPActorCritic,
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/tete/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Hoppper-v2

If you suspect this is an IPython 7.13.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56393,1],0]
  Exit code:    1
--------------------------------------------------------------------------
